# Setup
title: ~/mhadev/blog
# tagline: "A Jekyll theme"
baseurl: ""
paginate: 5
permalink: pretty
future: true

# About/contact
author:
  name: Mahmut Hilmi Arıkmert
  url: https://twitter.com/mharikmert
  email: contact@mharikmert.dev

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
